### PR TITLE
Added @Field documentation

### LINKED ISSUE #73: document @Field annotation
https://github.com/doctrine/phpcr-odm/pull/643

not sure how the versioning works in the docs .. I guess we also have a "since" markup ..?

### PR DESCRIPTION
**Pull request by dantleech**
Fixes #73 

See also: https://github.com/doctrine/phpcr-odm/pull/643

### CODE REVIEW

**Comment by dbu** [comment]
thanks! can we add a note that there used to be `@String` and so on, but these are deprecated because not compatible with php 7? they still work as long as people use php 5. otherwise people will be very confused when looking at older examples, or think the deprecated thing is a new convenience feature...

**Comment by lsmith77** [comment]
hmm we also mention ``@Property`` in the docs:
http://docs.doctrine-project.org/projects/doctrine-phpcr-odm/en/latest/reference/basic-mapping.html#property-mapping

does this make sense?

**Comment by dbu** [comment]
hm, did we duplicate `@Property` into `@Field`? if so, we should remove
the field thing again (unless we say we also want to deprecate Property
and move people to Field - as orm is using Field, being consistent with
them would have quite some value)

**Comment by lsmith77** [comment]
IIRC ``Property`` doesn't cover everything ..

/cc @WouterJ

**Comment by dantleech** [comment]
@dbu @lsmith77 the `@Property` annotation was abstract, so we assumed that it couldn't be used, and that `@Field` was a preferable name. /cc @WouterJ

**Comment by dantleech** [comment]
Just verified, using `@Property` gives: 

````
[Semantical Error] The class "Doctrine\ODM\PHPCR\Mapping\Annotations\Property" is not annotated with @Annotation.
````

**Comment by WouterJ** [comment]
See https://github.com/doctrine/phpcr-odm/issues/641#issuecomment-113470125 for a full discussion.

In short:
* Property is not correct, one would have to use TranslatedProperty
* Both these classes aren't annotations, they are just base classes for annotations.
* Making TranslatedProperty an annotation was not a really nice option because it's not a great name.
* Deprecating TranslatedProperty in favor of a new Field property was not a nice option as well, as many annotations (not only the type annotations) use this class as a base class.

Being BC and providing a new DX, I believe keeping Property and TranslatedProperty internal base classes and adding a Field annotation interface (=current state) is the best option.

**Comment by dantleech** [comment]
But, my mind has changed on this slightly. Doctrine uses `@Column` which is correct for an RDBMS. PHPCR should use `@Property` if it is to be consistent. To do this we would need to refactor the classes a little, but `@Property` would get my vote instead of `@Field` now.

**Comment by dbu** [comment]
see https://github.com/doctrine/phpcr-odm/pull/651

**Pull request merged**
